project:
  type: book

book:
  title: "Creating beautiful tables in R with {gt}"
  author: "Albert Rapp"
  date: today
  chapters:
    - index.qmd
    - getting_started.qmd
    - fancy_stuff.qmd
    - formatting.qmd
    - styling.qmd
    - case_studies.qmd
    - quarto_gt.qmd
  repo-url: https://github.com/AlbertRapp/gt_book
  cookie-consent: true
  google-analytics: G-Y3M69TZVPJ

format:
  html:
    tbl-cap-location: margin
    fig-cap-location: margin
    theme: 
      - theme.scss

knitr:
  opts_chunk: 
    collapse: true
    
editor: visual

